services:
  backend:
    build:
      context: ./backend
    container_name: tournamagic-backend
    ports:
      - "8080:8080"
    volumes:
      - backend_data:/app/backend/data

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: tournamagic-frontend
    ports:
      - "5174:80"
    depends_on:
      - backend

volumes:
  backend_data:
