spring:
  datasource:
    url: jdbc:h2:file:./backend/data/tournamagic;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

server:
  port: 8080
